[package]
name = "pafi"
version = "0.1.0"
authors = ["Fredrik <freddahf@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.7", default-features = true }
sdl2 = "0.34.2"
